<a href="https://colab.research.google.com/github/JakubDemeszko/ML_Course/blob/main/ML/deep_learning02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
from tensorflow.keras.models import Sequential
model = Sequential()
print(model)

In [4]:
# Siec budujemy dodajac wartstwy. Warstwa gesto polaczona to Dense, uzywamy funkcji add
# Units to liczba neuronow, w 1 wartswie podajemy input shape - liczba cech charakterystycznych
# w przypadku obrazow podajemy wymiar obrazow
from tensorflow.keras.layers import Dense
model.add(Dense(units = 4, input_shape=(10,)))

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
Total params: 44 (176.00 Byte)
Trainable params: 44 (176.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
# Dodanie kolejnej warstwy
model.add(Dense(units = 2))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
Total params: 54 (216.00 Byte)
Trainable params: 54 (216.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:
# Funkcje aktywacji, pozwala nam wrzucic neurony do uczenia, np relu zeruje wartosci ujemne
from tensorflow.keras.activations import linear
random_data = np.linspace(start = -3, stop = 3, num = 300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [9]:
px.line(data, x='data', y='linear', range_y = [-3,3])

In [10]:
model = Sequential()
model.add(Dense(units = 8, activation = 'relu', input_shape=(10,1)))
model.add(Dense(units = 1, activation = 'sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 10, 8)             16        
                                                                 
 dense_3 (Dense)             (None, 10, 1)             9         
                                                                 
Total params: 25 (100.00 Byte)
Trainable params: 25 (100.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
# Przed kompilacja modelu nalezy dodac rodzaj optymalizatora, funkcje straty oraz metryki do obserwacji podczas treningu
# Klasyfikacja binarna - przewidywanie 1 z 2 klas: np splata lub brak splaty kredyty
model.compile(optimizer = 'rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Klasyfikacja wieloklasowa: np rozpoznanie cyfr
model.compile(optimizer = 'rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
# regresja
model.compile(optimizer = 'rmsprop',
              loss='mse')

In [13]:
# Trenowanie modelu. Podajemy tutaj do trenowania tablice numpy
# Epochs: ile razy ma przejsc dana przez siec, batch size: rozmiar wsadu, validation split: podzial danych treningowych i walidacyjnych
# Klasyfikacja binarna, wygenerowanie danych
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size = (10000, 1))
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [15]:
# Tworzenie modelu klasyfikacji binarnej
model = Sequential()
model.add(Dense(units=32, activation = 'relu', input_shape = (150,)))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer = 'rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(data, labels, epochs = 20)

Epoch 1/20
313/313 [==============================] - 1s 2ms/step - loss: 0.7570 - accuracy: 0.4990
Epoch 2/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6984 - accuracy: 0.5419
Epoch 3/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6756 - accuracy: 0.5796
Epoch 4/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6603 - accuracy: 0.6053
Epoch 5/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6453 - accuracy: 0.6236
Epoch 6/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6308 - accuracy: 0.6479
Epoch 7/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6163 - accuracy: 0.6619
Epoch 8/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6019 - accuracy: 0.6792
Epoch 9/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5884 - accuracy: 0.6943
Epoch 10/20
313/313 [==============================] - 1s 3ms/step - loss: 0.5751 - accuracy: 0.7035

In [16]:
# Tworzenie modelu klasyfikacji binarnej, z dodaniem batch size wiekszego przy fit
model = Sequential()
model.add(Dense(units=32, activation = 'relu', input_shape = (150,)))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer = 'rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(data, labels, epochs = 20, batch_size = 64)

Epoch 1/20
157/157 [==============================] - 1s 2ms/step - loss: 0.7449 - accuracy: 0.5033
Epoch 2/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6977 - accuracy: 0.5441
Epoch 3/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6820 - accuracy: 0.5626
Epoch 4/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6704 - accuracy: 0.5923
Epoch 5/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6600 - accuracy: 0.6066
Epoch 6/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6503 - accuracy: 0.6226
Epoch 7/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6409 - accuracy: 0.6325
Epoch 8/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6314 - accuracy: 0.6504
Epoch 9/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6213 - accuracy: 0.6657
Epoch 10/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6115 - accuracy: 0.6773

In [17]:
# Tworzenie modelu klasyfikacji binarnej, dodanie parametru batch i validation split
# Tutaj otrzymujemy rowniez accuracy na zbiorze walidacyjnym
model = Sequential()
model.add(Dense(units=32, activation = 'relu', input_shape = (150,)))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer = 'rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(data, labels, epochs = 20, batch_size = 64, validation_split = 0.2)

Epoch 1/20
125/125 [==============================] - 1s 4ms/step - loss: 0.7537 - accuracy: 0.4996 - val_loss: 0.7240 - val_accuracy: 0.4920
Epoch 2/20
125/125 [==============================] - 0s 2ms/step - loss: 0.7013 - accuracy: 0.5385 - val_loss: 0.7153 - val_accuracy: 0.5055
Epoch 3/20
125/125 [==============================] - 0s 3ms/step - loss: 0.6831 - accuracy: 0.5686 - val_loss: 0.7137 - val_accuracy: 0.5040
Epoch 4/20
125/125 [==============================] - 0s 3ms/step - loss: 0.6700 - accuracy: 0.5895 - val_loss: 0.7142 - val_accuracy: 0.5030
Epoch 5/20
125/125 [==============================] - 0s 2ms/step - loss: 0.6587 - accuracy: 0.6056 - val_loss: 0.7181 - val_accuracy: 0.5020
Epoch 6/20
125/125 [==============================] - 0s 2ms/step - loss: 0.6481 - accuracy: 0.6233 - val_loss: 0.7189 - val_accuracy: 0.5065
Epoch 7/20
125/125 [==============================] - 0s 3ms/step - loss: 0.6376 - accuracy: 0.6400 - val_loss: 0.7231 - val_accuracy: 0.5015
Epoch 

In [20]:
# Verbose pokazuje obiekt history.
model = Sequential()
model.add(Dense(units=32, activation = 'relu', input_shape = (150,)))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer = 'rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
history = model.fit(data, labels, epochs = 20, batch_size = 64, validation_split = 0.2, verbose = 0)

In [21]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [22]:
model = Sequential()
model.add(Dense(units=32, activation = 'relu', input_shape = (150,)))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer = 'rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
history = model.fit(data, labels, epochs = 20, batch_size = 64, validation_split = 0.2, verbose = 1)

Epoch 1/20
125/125 [==============================] - 2s 9ms/step - loss: 0.7526 - accuracy: 0.4952 - val_loss: 0.7245 - val_accuracy: 0.5130
Epoch 2/20
125/125 [==============================] - 1s 4ms/step - loss: 0.7015 - accuracy: 0.5364 - val_loss: 0.7142 - val_accuracy: 0.5125
Epoch 3/20
125/125 [==============================] - 1s 5ms/step - loss: 0.6835 - accuracy: 0.5655 - val_loss: 0.7126 - val_accuracy: 0.5120
Epoch 4/20
125/125 [==============================] - 0s 4ms/step - loss: 0.6705 - accuracy: 0.5838 - val_loss: 0.7135 - val_accuracy: 0.5070
Epoch 5/20
125/125 [==============================] - 0s 2ms/step - loss: 0.6606 - accuracy: 0.5996 - val_loss: 0.7148 - val_accuracy: 0.5095
Epoch 6/20
125/125 [==============================] - 0s 2ms/step - loss: 0.6504 - accuracy: 0.6212 - val_loss: 0.7169 - val_accuracy: 0.5100
Epoch 7/20
125/125 [==============================] - 0s 3ms/step - loss: 0.6403 - accuracy: 0.6363 - val_loss: 0.7198 - val_accuracy: 0.5050
Epoch 

In [23]:
# Tworzenie danych testowych
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5,1))

In [24]:
# Predykcja, otrzymujemy prawdopodobienstwo danej klasy
model.predict(test_data)

1/1 [==============================] - 0s 85ms/step


array([[0.7731581 ],
       [0.506682  ],
       [0.43318275],
       [0.39979127],
       [0.41263086]], dtype=float32)

In [26]:
# Przewidywanie klasy
model.predict_classes(test_data)

AttributeError: 'Sequential' object has no attribute 'predict_classes'

In [28]:
# Klasyfikacja wieloklasowa
data = np.random.random((10000,150))
labels = np.random.randint(10, size=(10000,1))
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [29]:
# Zmiana label na kategorie (tyle num classes ile kategorii label)
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes = 10)
labels

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [31]:
# Tworzenie modelu, w 2 sense podajemy tyle ile mamy kategorii
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))
model.compile(optimizer = 'rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(data, labels, batch_size=32, epochs=100, validation_split=0.2)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 2.3170 - accuracy: 0.0949 - val_loss: 2.3022 - val_accuracy: 0.1060
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 2.3031 - accuracy: 0.1070 - val_loss: 2.3023 - val_accuracy: 0.1050
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 2.3012 - accuracy: 0.1061 - val_loss: 2.3049 - val_accuracy: 0.1105
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 2.2993 - accuracy: 0.1107 - val_loss: 2.3030 - val_accuracy: 0.1155
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 2.2964 - accuracy: 0.1184 - val_loss: 2.3098 - val_accuracy: 0.1140
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 2.2935 - accuracy: 0.1192 - val_loss: 2.3059 - val_accuracy: 0.1160
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 2.2927 - accuracy: 0.1240 - val_loss: 2.3067 - val_accuracy: 0.1115

In [32]:
# Predykcja
test_data = np.random.random((10,150))
model.predict(test_data)

1/1 [==============================] - 0s 50ms/step


array([[0.05589352, 0.06905862, 0.05376695, 0.0290498 , 0.04188811,
        0.0731651 , 0.325908  , 0.13832884, 0.18060456, 0.03233642],
       [0.18086775, 0.0443685 , 0.11037591, 0.09935786, 0.09335784,
        0.09800753, 0.13527247, 0.06605341, 0.05294606, 0.11939272],
       [0.14259787, 0.05869931, 0.14034654, 0.12085475, 0.26062402,
        0.08129185, 0.09594265, 0.08425331, 0.01274914, 0.0026405 ],
       [0.0802227 , 0.07483833, 0.21282783, 0.13410677, 0.05097378,
        0.09829967, 0.08893631, 0.05983998, 0.01536301, 0.18459168],
       [0.09037089, 0.09638129, 0.02646888, 0.06219784, 0.14785883,
        0.04243986, 0.07540458, 0.07605005, 0.25449672, 0.12833108],
       [0.18840225, 0.05369713, 0.05449452, 0.10492469, 0.04990921,
        0.31983626, 0.12328111, 0.03386025, 0.06209445, 0.00949996],
       [0.08232749, 0.09799156, 0.12307724, 0.05967594, 0.11428797,
        0.077441  , 0.1187627 , 0.08639816, 0.10530576, 0.13473223],
       [0.18760824, 0.0274785 , 0.0427208