<a href="https://colab.research.google.com/github/JakubDemeszko/ML_Course/blob/main/ML/deep_learning01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# Siec neuronowa sklada sie z: wagi, elementy modelu, ktore trenujemy.
# Funkcja aktywacji, funkcja straty (kontrola bledu), optymalizator (pozwala uczyc sie sieci)
# Przewidywanie liczb na podstawie modelu

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from tensorflow.keras.datasets.mnist import load_data
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

np.set_printoptions(precision = 12, suppress = True, linewidth = 120)
print(tf.__version__)

2.15.0


In [9]:
# Przygotowanie i zaladowanie danych
(X_train, y_train), (X_test, y_test) = load_data()
print(X_train[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 182 247 241   0   

In [10]:
X_train = X_train / 255.
X_test = X_test / 255.

In [13]:
# Budowa sieci neuronowej. Warstwy dodajemy metoda Add. Flatten - wyplaszcza nasze dane (by siec wiedziala czego sie spodziwac)
# Warstwa Dens - zawiera 128 neuronow
# Warstwa Dropout - porzuci 20% neuronow w warstwie
# Dodanie ponownie dens - 10 neuronow (tyle ile klas), aktywacja softmax - prawdopodobienstwo poszczegolnej klasy
# Kompilacja modelu
model = Sequential()
model.add(Flatten(input_shape = (28,28)))
model.add(Dense(units=128, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(units=10, activation = 'softmax'))

model.compile(optimizer='Adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_4 (Flatten)         (None, 784)               0         
                                                                 
 dense_8 (Dense)             (None, 128)               100480    
                                                                 
 dropout_4 (Dropout)         (None, 128)               0         
                                                                 
 dense_9 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101770 (397.54 KB)
Trainable params: 101770 (397.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
# Trenowanie modelu
history = model.fit(X_train, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2914 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1449 - accuracy: 0.9564
Epoch 3/5
1875/1875 [==============================] - 24s 13ms/step - loss: 0.1087 - accuracy: 0.9666
Epoch 4/5
1875/1875 [==============================] - 21s 11ms/step - loss: 0.0889 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 17s 9ms/step - loss: 0.0728 - accuracy: 0.9776


In [15]:
# Ocena modelu
model.evaluate(X_test, y_test, verbose = 2)

313/313 - 1s - loss: 0.0771 - accuracy: 0.9770 - 1s/epoch - 3ms/step


[0.07712670415639877, 0.9769999980926514]

In [16]:
metrics = pd.DataFrame(history.history)
metrics

loss  accuracy
0  0.291445  0.914850
1  0.144913  0.956383
2  0.108740  0.966633
3  0.088926  0.972183
4  0.072835  0.977550

In [19]:
# Wizualizacja - chcemy by strata nam malala, a accuracy roslo z kazda kolejna epoka
fig = make_subplots(rows = 2, cols = 1)
fig.add_trace(go.Scatter(y = metrics['loss'], name = 'loss'), row = 1, col = 1)
fig.add_trace(go.Scatter(y = metrics['accuracy'], name = 'accuracy'), row = 2, col = 1)
fig.update_layout(width = 800, height = 400)

In [20]:
# Predykcja na podstawie modelu
model.predict(X_test)

313/313 [==============================] - 1s 3ms/step


array([[0.00000010065 , 0.000000002536, 0.000003537496, ..., 0.9996685     , 0.000000308517, 0.000002775151],
       [0.000000008453, 0.0003546481  , 0.99963915    , ..., 0.            , 0.00000135371 , 0.            ],
       [0.000000064697, 0.9997575     , 0.000022784143, ..., 0.0001056331  , 0.000094229654, 0.000000049338],
       ...,
       [0.000000000008, 0.000000001156, 0.000000000018, ..., 0.000000891598, 0.00000099331 , 0.000017811813],
       [0.000000094503, 0.000000000225, 0.000000000135, ..., 0.000000000238, 0.00006695776 , 0.000000003502],
       [0.000000085722, 0.            , 0.000000002541, ..., 0.000000000023, 0.000000000272, 0.00000000001 ]],
      dtype=float32)

In [23]:
# Zwrocenie konkretnej klasy
y_pred_probabilities = model.predict(X_test)
y_pred = y_pred_probabilities.argmax(axis=-1)

print(y_pred)

313/313 [==============================] - 1s 3ms/step
[7 2 1 ... 4 5 6]


In [24]:
# Laczenie danych
pred = pd.concat([pd.DataFrame(y_test, columns=['y_test']), pd.DataFrame(y_pred, columns=['y_pred'])], axis = 1)
pred.head()

y_test  y_pred
0       7       7
1       2       2
2       1       1
3       0       0
4       4       4

In [25]:
# Wyciagniecie tego, gdzie jest zle
missclassified = pred[pred['y_test'] != pred['y_pred']]
missclassified.head()

y_test  y_pred
8         5       6
247       4       2
259       6       0
321       2       7
381       3       7