In [2]:
import pandas as pd
import numpy as np
import sklearn
import seaborn as sns

In [3]:
# Training data are the data which are used to train the model and then after training we can test it on the test data
# Other way: Data divided by: a) X_Train, b) X_Val (validation), c) X_test

np.random.seed(42)
np.set_printoptions(edgeitems = 30, linewidth=100000,
                    formatter = dict(float=lambda x: f'{x: 2f}'))
sns.set()

In [5]:
from sklearn.datasets import load_iris

raw_data = load_iris()
raw_data_copy = raw_data.copy()
raw_data_copy.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
data = raw_data_copy['data']
target = raw_data_copy['target']

print(f'{data[:5]}\n')
print(target[:5])

[[ 5.100000  3.500000  1.400000  0.200000]
 [ 4.900000  3.000000  1.400000  0.200000]
 [ 4.700000  3.200000  1.300000  0.200000]
 [ 4.600000  3.100000  1.500000  0.200000]
 [ 5.000000  3.600000  1.400000  0.200000]]

[0 0 0 0 0]


In [8]:
all_data = np.c_[data, target]
all_data[:5]

array([[ 5.100000,  3.500000,  1.400000,  0.200000,  0.000000],
       [ 4.900000,  3.000000,  1.400000,  0.200000,  0.000000],
       [ 4.700000,  3.200000,  1.300000,  0.200000,  0.000000],
       [ 4.600000,  3.100000,  1.500000,  0.200000,  0.000000],
       [ 5.000000,  3.600000,  1.400000,  0.200000,  0.000000]])

In [9]:
df = pd.DataFrame(data = all_data, columns = raw_data.feature_names + ['target'])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [10]:
df.describe().T.apply(lambda x: round(x, 2))

count  mean   std  min  25%   50%  75%  max
sepal length (cm)  150.0  5.84  0.83  4.3  5.1  5.80  6.4  7.9
sepal width (cm)   150.0  3.06  0.44  2.0  2.8  3.00  3.3  4.4
petal length (cm)  150.0  3.76  1.77  1.0  1.6  4.35  5.1  6.9
petal width (cm)   150.0  1.20  0.76  0.1  0.3  1.30  1.8  2.5
target             150.0  1.00  0.82  0.0  0.0  1.00  2.0  2.0

In [11]:
df.target.value_counts()

0.0    50
1.0    50
2.0    50
Name: target, dtype: int64

In [14]:
# Separating from the DF the last column target.
data = df.copy()
target = data.pop('target')
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [13]:
target.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: target, dtype: float64

In [18]:
# Splitting the data to the Train and Test samples
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(data, target, random_state = 42)

In [22]:
# Setting up the target value for the same values
X_train, X_test, Y_train, Y_test = train_test_split(data, target, random_state = 42, test_size = 0.1, stratify = target)
Y_train.value_counts()

0.0    45
2.0    45
1.0    45
Name: target, dtype: int64