<a href="https://colab.research.google.com/github/JakubDemeszko/ML_Course/blob/main/Numpy/numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Creating a basic array

x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [2]:
# Making 2D Array
x = np.array([[1,2,3], [3,3,3]])
x

array([[1, 2, 3],
       [3, 3, 3]])

In [3]:
# Making 3D array
x = np.array([[[1,2,3], [3,3,3], [5,5,5]]])
x

array([[[1, 2, 3],
        [3, 3, 3],
        [5, 5, 5]]])

In [4]:
# Checking the shape of Array
x.shape

(1, 3, 3)

In [5]:
# Creating an array with functions
np.zeros(shape = (3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones(shape = (2,2), dtype = 'int')

array([[1, 1],
       [1, 1]])

In [7]:
t = np.arange(15)
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
# Changing the shape of array
t.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
# Making operations on array (size have to be same)
A = np.array([3, 1, 4, 2])
B = np.array([3, 5, 7, 9])
print(A + B)

[ 6  6 11 11]


In [10]:
# Using methods to also get the same result
np.add(A, B)

array([ 6,  6, 11, 11])

In [11]:
# Using array multiplier
X = np.array([[1,3], [2,2]])
Y = np.array([[2,2], [0,4]])
np.dot(X, Y)

array([[ 2, 14],
       [ 4, 12]])

In [12]:
# Generating random seed to have the same score
np.random.seed(0)

In [13]:
# Making the array of elements from random distribution
np.random.randn(10, 4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275]])

In [14]:
# Random on precised values (0:1)
np.random.rand(10, 3)

array([[0.31542835, 0.36371077, 0.57019677],
       [0.43860151, 0.98837384, 0.10204481],
       [0.20887676, 0.16130952, 0.65310833],
       [0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959],
       [0.13818295, 0.19658236, 0.36872517],
       [0.82099323, 0.09710128, 0.83794491],
       [0.09609841, 0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552, 0.73926358],
       [0.03918779, 0.28280696, 0.12019656]])

In [15]:
# Using randint to make random array between particlar numebers
np.random.randint(low = 5, high = 100, size = 20)

array([28, 64,  7, 67, 40, 99, 72, 87, 51, 25, 86, 55, 32, 19, 46, 63, 70,
       41, 15, 91])

In [16]:
# Choice is getting random number from the element provided by us
np.random.choice([3,5,7,9])

9

In [17]:
# Getting the biggest value of the array
X = np.random.rand(10)
X[np.argmax(X)]

0.842342079667731

In [18]:
# Taking particular values by index
X[0:5]

array([0.0093567 , 0.84234208, 0.64717414, 0.84138612, 0.26473016])

In [19]:
X = X.reshape(2,5)
X

array([[0.0093567 , 0.84234208, 0.64717414, 0.84138612, 0.26473016],
       [0.39782075, 0.55282148, 0.16494046, 0.36980809, 0.14644176]])

In [20]:
# Cutting for Array which look different
X[0]

array([0.0093567 , 0.84234208, 0.64717414, 0.84138612, 0.26473016])

In [21]:
# Cutting the column
X[:, 0]

array([0.0093567 , 0.39782075])

In [22]:
# Getting 2 columns and 2 rows (from the middle)
X[:, 2:4]

array([[0.64717414, 0.84138612],
       [0.16494046, 0.36980809]])

In [23]:
# Iteration on array
for row in X:
  print(row)

[0.0093567  0.84234208 0.64717414 0.84138612 0.26473016]
[0.39782075 0.55282148 0.16494046 0.36980809 0.14644176]


In [24]:
for i in X.flat:
  print(i)

0.009356704856532616
0.842342079667731
0.6471741401875555
0.8413861191973544
0.26473016428344964
0.39782075275862905
0.5528214798875715
0.16494046024188413
0.36980809274834003
0.14644176272911225


In [31]:
# Creating a new array
A = np.arange(start = -10, stop = 10, step = 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [36]:
# MAking the logic mask to get particular data
np.bitwise_and(A > 0, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [37]:
# Cutting by the above mask
A[np.bitwise_and(A > 0, A < 5)]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])