<a href="https://colab.research.google.com/github/JakubDemeszko/ML_Course/blob/main/Numpy/numpy02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Making an vector
v1 = np.array([0, 4])
v1

array([0, 4])

In [3]:
# Calculating the length of the Vector in R2
np.linalg.norm(v1)

4.0

In [5]:
# Calculating the length in R3
v2 = np.array([0, 1, 5])
np.linalg.norm(v2)

5.0990195135927845

In [6]:
# Calculating the lenght between 2 points
v3 = np.array([5, 8])
np.linalg.norm(v1 - v3)

6.4031242374328485

In [7]:
# To multiply 2 array whe column number in A has to be same as row number in B
X = np.array([[2,3], [3,3]])
Y = np.array([[1], [-1]])
np.dot(X, Y)

array([[-1],
       [ 0]])

In [9]:
# Array determinant
np.linalg.det(X)

-3.0000000000000004

In [11]:
# Getting the reversed array
np.linalg.inv(X)

array([[-1.        ,  1.        ],
       [ 1.        , -0.66666667]])

In [12]:
# Array transposed
np.transpose(X)

array([[2, 3],
       [3, 3]])

In [14]:
# Equation system AX B
A = np.array([[2, 4],[1, -1]])
B = np.array([[1], [2]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

[[ 1.5]
 [-0.5]]
